
{
   if(true)
   {
      Unit_Effecter = §§newclass(Unit_Effecter,Unit);
   }
}

package
{
   public class Unit_Effecter extends Unit
   {
       
      
      public function Unit_Effecter(param1:*, param2:uint, param3:Number, param4:Number, param5:String, param6:String, param7:uint = 1, param8:Object = null)
      {
         super(param1,param2,param3,param4,param5,param6,param7,param8);
      }
      
      public function EnterFrame() : void
      {
         var _loc1_:uint = 0;
         if(true)
         {
            if(remove)
            {
               if(true)
               {
                  return;
               }
               addr115:
               _loc1_ = 0;
               loop1:
               while(true)
               {
                  if(_loc1_ >= enAr.length)
                  {
                     if(true)
                     {
                        §§push(!side);
                        if(true)
                        {
                           if(§§pop())
                           {
                              if(true)
                              {
                                 §§pop();
                                 if(true)
                                 {
                                    §§push(x + stats.wdth + stats.rangeX > endSpot);
                                    if(true)
                                    {
                                       addr196:
                                       if(§§pop())
                                       {
                                          if(true)
                                          {
                                             hitBase = true;
                                             if(true)
                                             {
                                                addr204:
                                                §§push(Boolean(side));
                                                if(true)
                                                {
                                                   if(§§pop())
                                                   {
                                                      §§pop();
                                                      if(true)
                                                      {
                                                         §§push(x - stats.wdth);
                                                         if(true)
                                                         {
                                                            §§push(§§pop() - stats.rangeX);
                                                         }
                                                         §§push(§§pop() < endSpot);
                                                      }
                                                      else
                                                      {
                                                         addr288:
                                                         _loc1_ = 0;
                                                         addr291:
                                                         while(_loc1_ < enAr.length)
                                                         {
                                                            if(enAr[_loc1_].dead)
                                                            {
                                                               while(true)
                                                               {
                                                               }
                                                               addr298:
                                                            }
                                                            else if(checkRange(enAr[_loc1_]))
                                                            {
                                                               while(true)
                                                               {
                                                                  attacking = enAr[_loc1_];
                                                                  addr310:
                                                                  while(true)
                                                                  {
                                                                     setAnim(name,"stand",0,stats.wlkFps,0);
                                                                  }
                                                               }
                                                               addr305:
                                                            }
                                                            while(true)
                                                            {
                                                               §§push(_loc1_ + 1);
                                                               break loop1;
                                                            }
                                                            break loop1;
                                                         }
                                                         addr333:
                                                         paintAnimation();
                                                         addr335:
                                                         paintNumbers();
                                                         return;
                                                         addr329:
                                                      }
                                                      §§goto(addr333);
                                                   }
                                                }
                                                if(§§pop())
                                                {
                                                   if(true)
                                                   {
                                                      hitBase = true;
                                                      if(true)
                                                      {
                                                         addr232:
                                                         if(hitBase)
                                                         {
                                                            if(true)
                                                            {
                                                               setAnim(name,"stand",0,stats.wlkFps,0);
                                                               if(true)
                                                               {
                                                                  addr246:
                                                                  §§goto(addr333);
                                                               }
                                                               else
                                                               {
                                                                  addr265:
                                                                  if(!hitBase)
                                                                  {
                                                                     setAnim(name,"walk",0,stats.wlkFps,0,false);
                                                                     addr285:
                                                                     §§goto(addr333);
                                                                  }
                                                                  §§goto(addr285);
                                                               }
                                                            }
                                                            setAnim(name,"stand",0,stats.wlkFps,0);
                                                            addr275:
                                                            §§goto(addr285);
                                                         }
                                                         §§goto(addr246);
                                                      }
                                                      §§goto(addr275);
                                                   }
                                                   §§goto(addr285);
                                                }
                                                §§goto(addr232);
                                             }
                                             §§goto(addr291);
                                          }
                                          §§goto(addr298);
                                       }
                                       §§goto(addr204);
                                    }
                                    else
                                    {
                                       addr254:
                                       if(!§§pop())
                                       {
                                          addr256:
                                          §§pop();
                                          addr261:
                                          if(!checkRange(attacking))
                                          {
                                             addr262:
                                             attacking = null;
                                             §§goto(addr265);
                                          }
                                       }
                                       §§goto(addr261);
                                    }
                                 }
                                 §§goto(addr305);
                              }
                              §§goto(addr256);
                           }
                           §§goto(addr196);
                        }
                        §§goto(addr256);
                     }
                     §§goto(addr310);
                  }
                  else
                  {
                     if(enAr[_loc1_].dead)
                     {
                        if(true)
                        {
                           continue;
                        }
                     }
                     else
                     {
                        if(!checkRange(enAr[_loc1_]))
                        {
                           continue;
                        }
                        if(true)
                        {
                           attacking = enAr[_loc1_];
                           if(true)
                           {
                              setAnim(name,"stand",0,stats.wlkFps,0);
                              if(true)
                              {
                                 continue;
                              }
                              §§goto(addr329);
                           }
                           §§goto(addr291);
                        }
                        §§goto(addr335);
                     }
                     §§goto(addr291);
                  }
               }
               while(true)
               {
                  _loc1_ = §§pop();
                  §§goto(addr291);
               }
            }
            else
            {
               §§push(Boolean(game.cmpPause));
               if(true)
               {
                  §§push(§§pop());
                  if(true)
                  {
                     if(!§§pop())
                     {
                        if(true)
                        {
                           §§pop();
                           if(true)
                           {
                              §§push(Boolean(game.pause));
                              if(true)
                              {
                                 addr40:
                                 if(§§pop())
                                 {
                                    if(true)
                                    {
                                       if(!didDeath)
                                       {
                                          if(true)
                                          {
                                             paintAnimation();
                                             if(true)
                                             {
                                                addr56:
                                                paintNumbers();
                                                if(true)
                                                {
                                                   return;
                                                }
                                                addr91:
                                             }
                                             else
                                             {
                                                addr96:
                                                status.EnterFrame();
                                                addr98:
                                                setMoveSpeed();
                                                §§push(!attacking);
                                                if(!attacking)
                                                {
                                                   addr104:
                                                   §§pop();
                                                   addr107:
                                                   if(!hitBase)
                                                   {
                                                      x += movMod * enSide;
                                                      §§goto(addr115);
                                                   }
                                                   else if(attacking)
                                                   {
                                                      if(true)
                                                      {
                                                         §§goto(addr254);
                                                         §§push(Boolean(attacking.dead));
                                                      }
                                                      §§goto(addr262);
                                                   }
                                                   else
                                                   {
                                                      if(hitBase)
                                                      {
                                                      }
                                                      §§goto(addr288);
                                                   }
                                                   §§goto(addr288);
                                                }
                                                §§goto(addr107);
                                             }
                                             §§goto(addr288);
                                          }
                                          §§goto(addr98);
                                       }
                                       else
                                       {
                                          doFadeDeath();
                                          if(true)
                                          {
                                             §§goto(addr56);
                                          }
                                          else
                                          {
                                             addr94:
                                             doStatusEffects();
                                             §§goto(addr96);
                                          }
                                       }
                                       §§goto(addr56);
                                    }
                                    §§goto(addr96);
                                 }
                                 else
                                 {
                                    doDmgNumbers();
                                    if(true)
                                    {
                                       if(didDeath)
                                       {
                                          if(true)
                                          {
                                             ++deathFade;
                                             doFadeDeath();
                                          }
                                       }
                                       else if(dead)
                                       {
                                          addr87:
                                          UnitFrame();
                                          paintAnimation();
                                          §§goto(addr91);
                                       }
                                       else
                                       {
                                          UnitFrame();
                                          §§goto(addr94);
                                       }
                                       §§goto(addr288);
                                    }
                                    §§goto(addr87);
                                 }
                              }
                              §§goto(addr96);
                           }
                           §§goto(addr107);
                        }
                        §§goto(addr104);
                     }
                     §§goto(addr40);
                  }
                  §§goto(addr96);
               }
               §§goto(addr104);
            }
            §§goto(addr288);
         }
         §§goto(addr115);
      }
   }
}
